apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter-headless
  namespace: gpu-operator
spec:
  clusterIP: None  # 👈 This makes it headless
  selector:
    app: nvidia-dcgm-exporter  # Ensure this matches the label of your exporter pods
  ports:
    - name: metrics
      port: 9400
      targetPort: 9400
