apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: dcornelius
spec:
  clusterIP: None 
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector:
    app: node-exporter
  