apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: torchx-cluster-role
rules:
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs/status"]
    verbs: ["get", "list", "watch"]
