apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv-torchx
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /media/nfs-codex/hpc/public/dcornelius
    server: nas
    readOnly: false
