apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-pvc
  namespace: dcornelius
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nas-pv
