apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-pvc
  namespace: torchx-worker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nas-pv-torchx
