apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dcornelius
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: "dcgm-exporter"
        kubernetes_sd_configs:
          - role: endpoints 
            namespaces:
              names: 
                - gpu-operator
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: dcgm-exporter-headless
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node

      - job_name: "node-exporter"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dcornelius
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node

      - job_name: "cadvisor"
        scheme: https
        metrics_path: /metrics/cadvisor
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: 
              - 172.20.20.1:10250
              - 172.20.20.2:10250
              - 172.20.20.3:10250
        metric_relabel_configs:
          - source_labels: [namespace]
            regex: "dcornelius|torchx-worker"
            action: keep
