apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources: 
      - pods
      - nodes
      - nodes/metrics
      - nodes/metrics/cadvisor
      - services
      - endpoints
    verbs: ["get", "list", "watch"]